const router = require("express").Router()
const dashboard_controller = require("../controllers/dashboard_controller")
const delete_account = require("../controllers/delete_account")
const get_connections = require("../controllers/get_connections")
const get_user_controller_handler = require("../controllers/get_user_controller")
const pair_user_handler = require("../controllers/pair_users")
const setup_profile = require("../controllers/setup_profile.controller")
const sign_in_controller = require("../controllers/sign_in_controller")
const sign_up_controller = require("../controllers/sign_up_controller")
const accept_connection = require("../controllers/accept_connection")
const delete_connection_request = require("../controllers/delete_connection_request")
const get_friends = require("../controllers/get_friends")
const send_connection_request = require("../controllers/send_connection_request")
const cancel_connection_request = require("../controllers/cancel_connection_request")
const delete_connection = require("../controllers/delete_connection")
const conversation = require("../controllers/fetch_conversation")
// User Authentication 

router.route("/sign-up").post(sign_up_controller)
router.route("/sign-in").post(sign_in_controller)
router.route("/dashboard").get(dashboard_controller)
router.route("/setup_profile").put(setup_profile)
router.route("/delete_account").delete(delete_account)
router.route("/pair_user").post(pair_user_handler)
router.route("/get_user/:id").get(get_user_controller_handler)
router.route("/get_connections").get(get_connections)
router.route("/accept_connection/:id").put(accept_connection)
router.route("/send_connection_request/:id").put(send_connection_request)
router.route("/delete_connection_request/:id").delete(delete_connection_request)
router.route("/cancel_connection_request/:id").delete(cancel_connection_request)
router.route("/get_friends").get(get_friends)
router.route("/delete_frined/:id").delete(delete_connection)
router.route("/get_convo/:id").get(conversation)

module.exports = router